services:
  mongolino:
    image: ghcr.io/smarzola/mongolino:latest
    command:
      - "--addr"
      - "0.0.0.0:27017"
      - "--db"
      - "/data/osv-proxy-malicious.db"
    volumes:
      - mongolino-data:/data
    ports:
      - "27018:27017"

  osv-proxy:
    image: ghcr.io/smarzola/osv-proxy:latest
    depends_on:
      - mongolino
    volumes:
      - ./osv-proxy.yaml:/etc/osv-proxy.yaml:ro
    command:
      - "serve"
      - "--config"
      - "/etc/osv-proxy.yaml"
    ports:
      - "8080:8080"

volumes:
  mongolino-data:
